### ISSUE TITLE
Faire cuire des rats déjà cuits pour avoir du scorched_stuff

### ISSUE THREAD

**Issue by sys4-fr** [sys4-fr/server-minetestforfun#12]
Cela pourrait servir de combustible comme le charbon.

Il me semble que le subgame Carbonne de @Calinou proposait cela. Et ça me plait bien.

**Comment by Calinou** [comment]
> Il me semble que le subgame Carbonne de @Calinou proposait cela. Et ça me plait bien.

Oui, en effet 🙂

**Comment by sys4-fr** [comment]
- Le scorched_stuff s'obtient en cuisant des rats déjà cuits.
- Il sert de combustible comme le charbon mais brule 2 fois plus vite.
- Il permet également de faire du colorant noir.

Remarque : J'ai découvert un bug dans le mod mobs_animal où la cuisson des rats est bien prévue mais ne fonctionnait pas. J'ai donc rajouté une correction dans ce commit pour y remédier.

Merci @Calinou pour ton petit commentaire et tes fonctionnalités que j'ai recopié ça fait bien plaisir ;)
