### ISSUE TITLE
Nourriture

### ISSUE THREAD

**Issue by Grossam** [sys4-fr/server-minetestforfun#19]
Salut, je ne sais pas quel mod est concerné au juste alors j'ouvre l'issue ici.

Certaines nourritures ne sont pas mangeables : le chili et des"pies" notamment.

Quand on le "mange" l'item disparaît bien de l'inventaire, mais on n'entend pas le "croc !" et la satiation n'augmente pas.

**Comment by sys4-fr** [comment]
Merci Grossam. C'est le bon endroit pour poster ce genre de problème. Si tu en trouve d'autres n'hésite pas bien sur.
Je pense que ça vient du mod Diet. Il ne doit pas supporter ces items qui sont assez récents. Je regarde ça au plus vite.
Merci.

**Comment by sys4-fr** [comment]
Bon ben c'était bien Diet qui posait problème. C'est corrigé :)
Commit : [5f7cd](https://github.com/sys4-fr/server-nalc/commit/5f7cd6271e4674b0e7a68b66ac1e66c7b8cecea6)
